### ISSUE TITLE
I love you! This is just what I need now!

### ISSUE THREAD

**Issue by phoenixg** [kirschbaum-development/nova-chartjs#23]

**Comment by phoenixg** [comment]
I hope there are more Chart types supported

**Comment by phoenixg** [comment]
I can't figure out how to use it, I have a Model, which has many fields, not January - December, but normal business fields, some fields of them has some integer value. How can I display it in Chart?

**Comment by navneetrai** [comment]
Hi @phoenixg 

I have updated the Readme with more details. You can specify custom parameters for you chart using the `parameters` setting in your [NovaChartJsSettings](https://github.com/kirschbaum-development/nova-chartjs#setup)
