### ISSUE TITLE
style is broken on digitalocean server

### ISSUE THREAD

**Issue by seoanalyze** [kirschbaum-development/nova-chartjs#32]
hey,
I uploaded my project with your nova-chartjs to a digitalocean server but I'm having a weird issue.
It seems that the styling of my chart is broken. I tried it local and everything works fine but as soon as I upload it to the digitalocean server the styling brokes.

Here is an image: https://www.wordpress-cologne.de/digitalocean.png

I'm thankful for any tips!

**Comment by navneetrai** [comment]
@seoanalyze We are using styles directly from chartjs.. we are not adding anything to it so I would most probably be something related to chartjs

Still I would try to test it.

**Comment by seoanalyze** [comment]
Moved everything to Forge and uploaded it via GitHub. Everything seems fine now :)
