### ISSUE TITLE
Bar Chart colours not showing

### ISSUE THREAD

**Issue by iMuMz** [kirschbaum-development/nova-chartjs#40]
Laravel Nova : 2.0.8
Nova Chart JS : 0.3.0

The colours for the bars do not show when adding additional datasets to the chart. The colours only display on the label when the user hovers over the chart.

When I change the type to Line then the colours display correctly.

![Screenshot 2019-11-29 at 14 34 41](https://user-images.githubusercontent.com/22936672/69869602-f5c60f80-12b5-11ea-9762-42a125282c6c.png)

**Comment by brandonferens** [comment]
@iMuMz That is interesting. Have you made any changes to other css or js on your site that could per chance cause those issues or is this a clean install of Nova? 

And this sounds like it is caused primarily by the bar chart?

Would you please share the packages you have installed through composer so we can test this locally? I'd like to try and duplicate what you have and see if it is this package or a conflict with another package.

**Comment by iMuMz** [comment]
@brandonferens I did not make any changes to other css or js, only the css for the custom nova theme.

This is only an issue when using the bar chart.

I installed a fresh copy of Nova to see if the issue remains, which it does. Only the labels show the correct colour.

Laravel Nova : 2.8.0
Nova Chart JS : 0.3.0

Composer packages :

 "php": "^7.2",
 "fideloper/proxy": "^4.0",
 "kirschbaum-development/nova-chartjs": "^0.3.0",
 "laravel/framework": "^6.2",
 "laravel/nova": "~2.0",
 "laravel/tinker": "^1.0"

![Screenshot 2019-12-06 at 08 53 54](https://user-images.githubusercontent.com/22936672/70302905-e7707a00-1806-11ea-8fee-de515e7f49cc.png)

**Comment by brandonferens** [comment]
@iMuMz Thank you for that information. We will look into this and fix as we are able to. In the meantime if you figure out the issue, please feel free to issue a PR for the fix.

**Comment by brandonferens** [comment]
@iMuMz Would you mind posting all the code for your `getAdditionalDatasets()` method?

**Comment by iMuMz** [comment]
@brandonferens 

```
/**
     * Return a list of additional datasets added to chart
     *
     * @return array
     */
    public function getAdditionalDatasets(): array
    {
        return [
            [
                'label' => 'Average Sales',
                'borderColor' => '#FF3936',
                'color' => '#FF3936',
                'data' => [80, 40, 62, 79, 80, 90, 79, 90, 90, 90, 92, 91],
            ],
        ];
    }
```

**Comment by brandonferens** [comment]
@iMuMz That is what I was suspecting. In order to make colors work for bar charts you must set the `backgroundColor` option. Here is an example
```php
/**
  * Return a list of additional datasets added to chart
  *
  * @return array
  */
public function getAdditionalDatasets(): array
{
    return [
        [
            'label' => 'Average Sales',
            'borderColor' => '#FF3936',
            'color' => '#FF3936',
            'backgroundColor' => '#FF3936'
            'data' => [80, 40, 62, 79, 80, 90, 79, 90, 90, 90, 92, 91],
        ],
    ];
}
```

Let me know if this helps you out!

**Comment by iMuMz** [comment]
@brandonferens That works perfectly, thank you

**Comment by brandonferens** [comment]
Glad to here it!
