### ISSUE TITLE
Comparison Data does not load

### ISSUE THREAD

**Issue by iMuMz** [kirschbaum-development/nova-chartjs#66]
Laravel Nova : 4.22.2
Nova Chart JS : 2.0.0

I am having trouble loading the comparison data, nothing is shown in the logs with or without data.

```
 * Return a list of all models available for comparison to root model
     *
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public static function getNovaChartjsComparisonData($chartName = 'default'): array
    {

        Log::debug('Comparison data..');
        Log::debug('Chart name..'.$chartName);

    }
```

I also added the $chartName as a parameter, which does not seem to be in the readme.

```
Declaration of App\Model::getNovaChartjsComparisonData(): array must be compatible with KirschbaumDevelopment\NovaChartjs\Contracts\Chartable::getNovaChartjsComparisonData($chartName = 'default'): array
```

Not sure what I am doing wrong?

**Comment by wilkerwma** [comment]
@iMuMz It's probably because you not returning an `array` from this function. 
adding a simple `return [];` should be enough for your testing. 

I'm closing this one, but feel free to open it again if you still need help.

**Comment by iMuMz** [comment]
@wilkerwma Thank you for the response, however I still have the same issue.

```
     /**
     * Return a list of all models available for comparison to root model
     *
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public static function getNovaChartjsComparisonData($chartName = 'default'): array
    {

        Log::debug('Comparisons');
        Log::debug('Chart name..'.$chartName);

        return [];
     }
```

The logs are empty, and the method isn't being called.
